version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-cadastro-de-ninjas
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    container_name: app-cadastro-de-ninjas
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always